### ISSUE TITLE
Add PRE-COMMIT-001: Pre-commit Hooks Exclude External Tools

### ISSUE THREAD

**Issue by ozand** [ozand/shared-knowledge-base#13]
## Proposed Entry

**ID:** PRE-COMMIT-001
**Title:** Pre-commit Hooks Exclude External Tools
**Category:** Universal
**Severity:** Medium
**Scope:** Universal

**Pattern:** Projects using external tools, vendored code, or git submodules must exclude them from project-specific linting rules.

**Validation:** ✅ Passed YAML syntax validation

---

## Real-World Example

**Project:** CompanyBase ETL - Shared Knowledge Base v3.0 Upgrade
**Date:** 2026-01-06
**Issue:**

After upgrading Shared KB submodule from v2.0 to v3.0, pre-commit hooks failed on `docs/knowledge-base/tools/kb.py`:

```
❌ ruff: Found 29 errors (26 fixed, 3 remaining)
   docs\knowledge-base\tools\kb.py:31: UP035
   docs\knowledge-base\tools\kb.py:628: F811 Redefinition of 'os'

❌ mypy: Found 39 errors in 1 file
   docs\knowledge-base\tools\kb.py:33: Library stubs not installed for "yaml"
   docs\knowledge-base\tools\kb.py:125: "list" is not subscriptable
```

**Root Cause:**

The `.pre-commit-config.yaml` had no exclusions:

```yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
```

This applied to ALL files, including:
- `docs/knowledge-base/shared/*` (submodule)
- `docs/knowledge-base/tools/kb.py` (copied from submodule)

**Impact:**
- Could not commit Shared KB v3.0 upgrade
- External tool code shouldn't be modified to fit project standards
- Each submodule update would require manual fixing

**Solution Applied:**

```yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^docs/knowledge-base/tools/  # ← ADDED
      - id: ruff-format
        exclude: ^docs/knowledge-base/tools/  # ← ADDED

  - repo: https://github.com/pre-commit/mirrors-mypy
    hooks:
      - id: mypy
        exclude: ^docs/knowledge-base/         # ← ADDED
```

Result: ✅ Commit succeeded

---

## Why This Pattern Is Universal

This issue affects **ANY** project with:
- Git submodules (Shared KB, vendored libraries)
- External tools (copied from dependencies)
- Auto-generated code (protobuf, OpenAPI, etc.)
- Third-party code in repository

**Common scenarios:**
1. Shared KB integration (like our case)
2. Vendored dependencies (vendor/)
3. Generated code (generated/, *.pb.go)
4. External tools (tools/, external/)
5. Framework templates (scaffolding/)

**Not project-specific** - universal git/submodule/pre-commit pattern.

---

## Solutions Provided (Full YAML)

The YAML file includes 4 solution approaches:

1. **Configuration-based** (RECOMMENDED)
   - Add `exclude:` patterns in `.pre-commit-config.yaml`
   - Examples for common directories
   - Regex patterns explained

2. **Gitattribute-based**
   - Use `.gitattributes` to mark files as generated
   - `linguist-generated`, `linguist-vendored` tags
   - Note: Pre-commit requires explicit config

3. **Directory-based**
   - Organize external code in separate directories
   - Clear project structure
   - Easy to exclude entire trees

4. **Hook-specific**
   - Disable specific hooks for files
   - Fine-grained control
   - When only some hooks should be skipped

**Additional sections:**
- Best practices (directory structure, config, documentation)
- Common mistakes (wrong vs right approaches)
- Testing strategies (verify exclusions work)
- Real-world examples (KB integration, vendor libraries, generated code)
- Monitoring (track excluded files, linter errors)
- Alternatives (private linter config, separate repos)

---

## Impact

**Without this pattern documented:**
- Teams comment out hooks entirely (loses code quality)
- Teams modify external code (lost on updates)
- Teams add individual file exclusions (hard to maintain)
- CI/CD fails on submodule updates
- Merge conflicts from auto-formatting

**With this pattern in Shared KB:**
- Standard exclusion patterns
- Multiple approaches with trade-offs
- Testing strategies
- Anti-patterns documented
- All projects with submodules benefit

---

## Suggested Actions

1. **File location:** `universal/patterns/pre-commit-exclude-external.yaml`
2. **Scope:** `universal` (applies to all languages, all projects)
3. **Priority:** Medium (common issue, documented solution exists)
4. **Related entries:**
   - git-lfs-001: GitHub Large File Detection
   - universal-gitignore-001: Database Separation from Code
   - TEST-003: Hardcoded File Paths in Tests

---

## Additional Context

**Pre-commit configuration best practices:**
```yaml
# Common exclusion patterns:
exclude: ^docs/knowledge-base/    # Exclude entire directory
exclude: ^vendor/                  # Vendored dependencies
exclude: ^third_party/            # Third-party code
exclude: ^generated/              # Auto-generated files
```

**Testing validation:**
```bash
# Verify exclusions work:
pre-commit run --files external/tool.py        # Should skip
pre-commit run --files src/project.py          # Should run
pre-commit run --verbose --files external/     # Check why
```

**Statistics from our case:**
- External file size: 44KB (kb.py from Shared KB)
- Linter errors: 68 total (29 ruff + 39 mypy)
- Time to investigate: ~15 minutes
- Time to fix: ~5 minutes (add 3 exclude lines)
- Time wasted without documentation: ~20 minutes

---

## Files Referenced

The complete YAML file is located at:
```
docs/knowledge-base/shared/universal/patterns/pre-commit-exclude-external.yaml
```

File size: 9.2KB
Sections: 12 (symptoms, root_cause, real_world_example, solutions, best_practices, common_mistakes, testing, real_world_examples, monitoring, alternatives, references, related_entries)

---

**Created by:** Project Agent (CompanyBase ETL)
**Date:** 2026-01-06
**Validation:** ✅ YAML syntax valid
**Real-world:** ✅ Production blocker during Shared KB v3.0 migration
**Reusability:** ✅ Universal pattern for all projects with external code

**Curator action:** Please review and merge to Shared KB universal/patterns/

---

## Additional Notes for Curator

This pattern is especially relevant for:
- Anyone integrating Shared KB as a submodule
- Projects using vendored dependencies
- Teams with auto-generated code in repo
- CI/CD pipelines that run pre-commit

The real-world example includes:
- Exact error messages
- Before/after configuration
- Impact analysis
- Working solution

**Comment by ozand** [comment]
## 📋 Curator Review: Issue #13

### Status: ❌ Incomplete - YAML File Missing

**Problem:** The referenced YAML file does not exist in the repository.

### Expected File
- **Path:** `universal/patterns/pre-commit-exclude-external.yaml`
- **Status:** ❌ File not found

### Issue Analysis

The issue description states:
> "The complete YAML file is located at:  
> `docs/knowledge-base/shared/universal/patterns/pre-commit-exclude-external.yaml`  
> File size: 9.2KB"

However, this file was **not committed** to the shared-knowledge-base repository.

### Pattern Content Review

Based on the issue description, **PRE-COMMIT-001** would cover:
- **Title:** "Pre-commit Hooks Exclude External Tools"
- **Problem:** Projects using external tools, vendored code, or git submodules must exclude them from project-specific linting rules
- **Real-world example:** Shared KB v3.0 upgrade failing on submodule files
- **Uniqueness:** ✅ NOT covered by existing patterns (verified: no pre-commit exclusion patterns found)

**Value assessment:**
- ✅ Universal pattern (applies to all languages, all projects)
- ✅ Real production blocker with clear solution
- ✅ Comprehensive (12 sections planned)
- ✅ Multiple solution approaches documented

**Common scenarios covered:**
1. Shared KB integration (submodule)
2. Vendored dependencies (vendor/)
3. Generated code (generated/, *.pb.go)
4. External tools (tools/)
5. Framework templates (scaffolding/)

### Resolution

❌ **Closing as incomplete** - The YAML file referenced in the issue does not exist in the repository.

**Next steps for contributor:**
1. Provide the actual YAML file content (9.2KB with 12 sections)
2. Create a GitHub issue with the YAML content embedded directly
3. Follow AGENT-HANDOFF-001 workflow: Create issue with full YAML in body, not external file reference

**Pattern ID PRE-COMMIT-001 reserved** for future submission with complete YAML content.

---

**Real-world impact from issue:**
- Linter errors: 68 total (29 ruff + 39 mypy)
- Time to investigate: ~15 minutes
- Time to fix: ~5 minutes (add 3 exclude lines)
- Time wasted without documentation: ~20 minutes

This pattern would save teams ~20 minutes per integration, plus prevent CI/CD failures.

**Related patterns:**
- AGENT-HANDOFF-001 (proper contribution workflow)
- GIT-SUBMODULE-001 (submodule integration)
- Existing patterns: None cover pre-commit exclusions

**Comment by ozand** [comment]
Closing as incomplete - YAML file not found.

The referenced file `universal/patterns/pre-commit-exclude-external.yaml` does not exist in the repository.

**Pattern value:** ✅ High-value universal pattern
- Saves teams ~20 minutes per external tool integration
- Prevents CI/CD failures on submodule updates
- Real production blocker with clear solution

**Next steps:**
- Contributor should provide 9.2KB YAML content directly in issue body
- Or resubmit following AGENT-HANDOFF-001 workflow

**Pattern ID PRE-COMMIT-001 reserved** for future submission with complete YAML content.
